### ISSUE TITLE
Auto Placement of Equipment

### ISSUE THREAD

**Issue by ThunderSniper** [Lordmau5/Carry-Stacker-Reloaded#2]
Sorry I commented instead posting the issue!

Carry Stacker Reloaded Version:
R6
Offline or Online?:
Both
What happens / happened?:
When trying to throw any bags that are carried and holding more than a single bag you may trigger a gltich that will happen whenever you then proceed to pick up a bag when you aren't carrying one.

The first glitch is that you will pick up the bag and then attempt to place your equipment that you have selected, this is a pain for ECM Jammers especially!

The second problem comes when you may throw two bags instead of one, this is not a case of me holding 'G' for too long, it simply forces you to throw two of the items.
How can I potentially reproduce it?:
Following the steps I've detailed there, host your own game and attempt to pick up more than a few bags, I find Art Gallery to work very well as you can hold several paintings. Then hold 'G' to throw them all constantly in a nice stream as we were able to before, you will find that after doing this once and emptying your carry capacity you will attempt to place your equipment when you pick up a bag.

The throwing glitch occurs randomly but appears to be activated at the same time that equipment is auto-placed.

**Comment by nolancs** [comment]
@Lordmau5 @ThunderSniper 

Guys you can fix this by deleting the PlayerManager:update function in playermanager.lua, or just comment out the code that causes the bug

`Carry Stacker Reloaded / lua / playermanager.lua`

```lua
function PlayerManager:update(t, dt)
    master_PlayerManager_update(self, t, dt)

    -- // Disabling this code fixes the double throw and use equipment item on pick up bugs
    -- if nextUpdate == nil or t < nextUpdate then
    --     return
    -- end
    --
    -- if PlayerStandard == nil or PlayerStandard.use_item_held == nil then return end
    --    if PlayerStandard:use_item_held() then
    --    drop_and_set_carry(self, drop_all_carry_args)
    -- end
end
```

**Comment by Lordmau5** [comment]
That's the quick fix, yes. 

However, I'm still struggling with keeping it in whilst also keeping compatibility...

**Comment by ThunderSniper** [comment]
@nolancs @Lordmau5 Awesome, as a quick fix at least the mod returns to being as useful as it was! I was having some problems with this equipment placing. I'll keep an eye on here in case you manage to release a fix. Thank you!

**Comment by josephting** [comment]
@Lordmau5 Do you have any idea yet? I was looking at the codes and tried fixing it and it seems like if `drop_and_set_carry` is called when `#stack_table` is 0, the `use_item` seems to be held down after picking up a loot again.

If you only tap drop item lightly and not having `drop_and_set_carry` called whilst `#stack_table` is 0, everything will be fine.

Couldn't get it fixed yet though will try again when I have more time.
